# Generated by Django 5.0.6 on 2024-05-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queue_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="queueentry",
            name="invited",
            field=models.BooleanField(default=False),
        ),
    ]
