# Generated by Django 5.0.6 on 2024-05-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queue_app", "0002_queueentry_invited"),
    ]

    operations = [
        migrations.AddField(
            model_name="queueentry",
            name="desk",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
